version: "3.7"
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
    ports:
      - "${API_PORT}:80"
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - db
  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - 3306
