version: "3.7"
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    ports:
      - "${API_PORT}:80"
    volumes:
      - ./api:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - db
  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - 3306
  react-admin:
    build:
      context: .
      dockerfile: docker/node/admin/Dockerfile
    volumes:
      - ./react/admin:/app
    env_file:
      - .env
    environment:
      - PORT=${APP_ADMIN_PORT}
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - ${APP_ADMIN_PORT}:${APP_ADMIN_PORT}
    expose:
      - ${APP_ADMIN_PORT}
    stdin_open: true
  react-blog:
    build:
      context: .
      dockerfile: docker/node/blog/Dockerfile
    volumes:
      - ./react/blog:/app
    env_file:
      - .env
    environment:
      - PORT=${APP_BLOG_PORT}
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - ${APP_BLOG_PORT}:${APP_BLOG_PORT}
    expose:
      - ${APP_BLOG_PORT}
    stdin_open: true
